### ISSUE TITLE
Exercise 0.12 code typo

### ISSUE THREAD

**Issue by pedropolvora** [LxMLS/lxmls_guide#101]
I believe that on the ```gradient_descent``` function on line 13 it should be 
``` x_new = x_old - step_size * get_grad(x_new) ``` and not ``` x_new = x_old - step_size * grad(x_new)``` and also it should be ```get_y``` and not ```func``` on the lines 14-15

**Comment by pedropolvora** [comment]
nevermind those are argumentt ....

**Comment by andre-martins** [comment]
Actually it should probably be x_new = x_old - step_size * get_grad(x_old)
and not x_new = x_old - step_size * get_grad(x_new)... Even if x_new =
x_old the get_grad(x_old) syntax is clearer.

(Even better: simply  x -= step_size * get_grad(x).)

2016-07-21 15:39 GMT+01:00 Pedro <notifications@github.com>:

**Comment by ramon-astudillo** [comment]
somebody wants do to a PR for that?
