### ISSUE TITLE
Implementation of Viterbi

### ISSUE THREAD

**Issue by mttk** [LxMLS/lxmls_guide#102]
At the assignment 2.5, page 58 in the guide - the implementation of the Viterbi algorithm needs to be done while working in the log domain, while the pseudocode is written for the regular domain (so, in code - we need to add instead of multiply, and that isn't mentioned anywhere before, or at the excercise).

**Comment by ramon-astudillo** [comment]
It is left clear in page 50. A detailed description of operations in log-domain is given in page 51 (section 2.4.1). Plus Exercise 2.4 is only about operations in log-domain.
