### ISSUE TITLE
Day 2 sufficient statistics sanity check

### ISSUE THREAD

**Issue by beckdaniel** [LxMLS/lxmls_guide#56]
In Day 2, page 46, the sanity checks says that both transition/final counts and emission counts should sum to MN. However, isn't this assuming that N is fixed for every sequence, when in practice it can vary? The equations for the transition and emission counts also seem odd to me since N is present in the second summation. Instead of

\sum_{m=1}^M \sum_{i=1}^N

shouldn't it be something like

\sum_{m=1}^M \sum_{i=1}^len(M)

?

**Comment by ramon-astudillo** [comment]
This seems to be the case, could you please fix it?.

**Comment by beckdaniel** [comment]
Yes, no problem.
