### ISSUE TITLE
Small typos deep learning part

### ISSUE THREAD

**Issue by davidbp** [LxMLS/lxmls_guide#62]
1) Page 101 form the draft_may25.pf

![screen shot 2015-05-26 at 12 46 42](https://cloud.githubusercontent.com/assets/4223580/7810771/4bc56ed2-03a5-11e5-95f3-295999140f03.png)

- figure 7.1 states that z = l(x)
- (7.2) states that z = g(x).

2) Should we change figure 7.1  and write z = g(x) ? 

3) sum over k' from 1 to K ( 1=k' must be changed by k' =1 in the underscript of the sum):
![screen shot 2015-05-26 at 17 05 11]

4) Equation 7.4 p(y_k |x ) =( f_k o g_k) (x) instead of p(y_k |x ) =( f_k o g) (x) since g (x) is the net input (vector) and f_k is applied to the k'th component of the net input. Therefore f_k( g_k (x) ) = p(y_k | x)

(https://cloud.githubusercontent.com/assets/4223580/7815554/6701beb6-03c9-11e5-9a8b-d1c9e2c64b54.png)

Maybe this should be rewritten as a vector to enfasize and faciltate reading. For example:
![latex-image-1](https://cloud.githubusercontent.com/assets/4223580/7815840/244d84ae-03cb-11e5-954e-76dca5ef8a8d.png)

note) Page 101 (this is not a typo but an extrage way to write the bias). Why don't we write the bias as b instead of w?  In the logistic regression example in theano's website the bias is written as b.

**Comment by ramon-astudillo** [comment]
Yes, please correct those two.
