### ISSUE TITLE
for loop missing in the backward algorithm

### ISSUE THREAD

**Issue by davidbp** [LxMLS/lxmls_guide#70]
In the current version of the pseudocode of backward algorithm we have
![screen shot 2015-06-12 at 20 21 31](https://cloud.githubusercontent.com/assets/4223580/8137062/ee445058-1140-11e5-8bb5-e291eed99d0b.png)

where c_l is not specified. Should it be something like this?

![screen shot 2015-06-12 at 20 24 18](https://cloud.githubusercontent.com/assets/4223580/8137093/3284877e-1141-11e5-8a37-81caedbb0753.png)

This is relevant. I have create an issue in the lxmls_toolkit since:
- the emission probabilities are outside the logsum in the forward algorithm 
- the emission probabilities are inside the logsum in the backward algorithm

Maybe this  detail about the logsum is already correct. I am sure anyway that the loop over the different states is needed.

**Comment by ramon-astudillo** [comment]
The code is right. Have a look at Eq 25 in http://www.gao.ece.ufl.edu/eel6825/rabiner_hmm.pdf  

for a more general view on why this is like this see

http://www.stat.columbia.edu/~liam/teaching/neurostat-fall14/papers/hmm/minka-lds-techreport.pdf

**Comment by davidbp** [comment]
THe code might be right but what about the pseudocode of the algorithm?
In the code the is a double for in both the forward and the backward algorithms but the pseudocode given just has a for in the backward algorithm.

**Comment by ramon-astudillo** [comment]
Ok, that part seems to be wrong, yes. So the parenthesis are ok, but there is indeed a missing for. Could you please ad it?.

**Comment by davidbp** [comment]
Corrected with pull request
