### ISSUE TITLE
Exercise 5.1 referencing ex 6.1 

### ISSUE THREAD

**Issue by davidbp** [LxMLS/lxmls_guide#95]
In ex 5.1 there is a reference

    You can test the different models with the same sentiment analysis problem as
    in Exercise 6.1. 

It seems to me that it's wrong because 6.1 is about part of speech tagging.
Should we just remove it?

**Comment by davidbp** [comment]
There is actually a much better way.

Please write \label{Ex5.1} inside exercise 5.1 and then ref{Ex5.1} This way we ensure future resistance to the references.

This must be done in Ex 5.4 where all the references are bad:

We first see an example that does not use any of the code in TheanoMLP but
rather continues from what you wrote in exercise 6.3. In this exercise you
completed a sigmoid layer with Theano. To get some values for the weights we
used the first layer of the network you trained in 6.2. now we are going to use
the second layer as well. This is thus assuming that your network in 6.2 has
only two layers e.g. the recommended geometry (I, 20, 2). Make sure this is the
case before starting this exercise.  

should be changed for 5.k not 6.k

**Comment by ramon-astudillo** [comment]
Yes, that is much better, could you do a PR for that?

**Comment by ramon-astudillo** [comment]
Did it myself, closing this
